### PR TITLE
reduce range of unicode

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
before: 
```
isChinese("扁担宽，板凳长，扁担想绑在板凳上。") x 11,562,495 ops/sec ±0.56% (88 runs sampled)
isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。") x 41,004,072 ops/sec ±2.48% (87 runs sampled)
isChinese("扁担宽，板凳长，扁担想绑在板凳上。ss") x 29,389,279 ops/sec ±2.31% (88 runs sampled)
isChinese(chars1000) true x 332,923 ops/sec ±1.06% (89 runs sampled)
isChinese(chars1000WithS) false x 1,690,598 ops/sec ±1.35% (86 runs sampled)
Fastest is isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。")
```

after:
```
isChinese("扁担宽，板凳长，扁担想绑在板凳上。") x 11,947,991 ops/sec ±0.45% (90 runs sampled)
isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。") x 42,548,217 ops/sec ±1.18% (89 runs sampled)
isChinese("扁担宽，板凳长，扁担想绑在板凳上。ss") x 30,718,944 ops/sec ±0.48% (90 runs sampled)
isChinese(chars1000) true x 375,754 ops/sec ±0.47% (90 runs sampled)
isChinese(chars1000WithS) false x 1,746,008 ops/sec ±0.89% (88 runs sampled)
Fastest is isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。")
```

### CODE REVIEW

**Comment by alsotang** [comment]
The data structure looks asymmetric and this optimization is hard-coded. While the performance improvement is pretty obvious, could it be a little more graceful?

**Comment by IWANABETHATGUY** [comment]
```js
function generatePunctuation() {
  // Chinese punctuation
  const punctuation = [
    [0xff0c, 0xff0c], //，
    [0x3002, 0x3002], //。
    [0x00b7, 0x00b7], //·
    [0x00d7, 0x00d7], //×
    [0x2014, 0x2014], //—
    [0x2018, 0x2018], //‘
    [0x2019, 0x2019], //’
    [0x201c, 0x201c], //“
    [0x201d, 0x201d], //”
    [0x2026, 0x2026], //…
    [0x3001, 0x3001], //、
    [0x300a, 0x300a], //《
    [0x300b, 0x300b], //》
    [0x300e, 0x300e], //『
    [0x300f, 0x300f], //』
    [0x3010, 0x3010], //【
    [0x3011, 0x3011], //】
    [0xff01, 0xff01], //！
    [0xff08, 0xff08], //（
    [0xff09, 0xff09], //）
    [0xff1a, 0xff1a], //：
    [0xff1b, 0xff1b], //；
    [0xff1f, 0xff1f], //？
  ];
  // auto merge here
  punctuation.sort((a, b) => a[0] - b[0]);
  const mergedPunctuation = punctuation.reduce((acc, cur) => {
    if (acc.length === 0) {
      return [cur]
    }
    const last = acc[acc.length - 1];
    if (last[1] + 1 === cur[0]) {
      last[1] += 1;
      return acc
    } else {
      return [...acc,[...cur] ] 
    }
  }, []);
  return mergedPunctuation
}

```
add this auto merge function may grace a bit , but introduce more overhead
```bash
isChinese("扁担宽，板凳长，扁担想绑在板凳上。") x 11,494,987 ops/sec ±0.54% (90 runs sampled)
isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。") x 44,003,270 ops/sec ±0.82% (91 runs sampled)
isChinese("扁担宽，板凳长，扁担想绑在板凳上。ss") x 30,746,330 ops/sec ±0.51% (87 runs sampled)
isChinese(chars1000) true x 340,523 ops/sec ±0.48% (90 runs sampled)
isChinese(chars1000WithS) false x 1,741,193 ops/sec ±0.93% (90 runs sampled)
```

**Comment by IWANABETHATGUY** [comment]
if you agree , i will update  the pr

**Comment by alsotang** [comment]
This modify is good. The overhead only happens when library initial, so it's ok. 
Just assure the combined result is correct and I will merge this.

**Comment by IWANABETHATGUY** [comment]
ready to merge

**Comment by alsotang** [comment]
I checked out this commit and compare the benchmark with master

```shell
$ node -v
v16.4.0
```

```shell
# master
isChinese("扁担宽，板凳长，扁担想绑在板凳上。") x 10,532,167 ops/sec ±0.84% (87 runs sampled)
isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。") x 41,371,203 ops/sec ±0.74% (91 runs sampled)
isChinese("扁担宽，板凳长，扁担想绑在板凳上。ss") x 28,886,915 ops/sec ±0.98% (88 runs sampled)
isChinese(chars1000) true x 317,638 ops/sec ±0.89% (87 runs sampled)
isChinese(chars1000WithS) false x 1,611,493 ops/sec ±0.99% (88 runs sampled)
```

```shell
# fd03bbd
isChinese("扁担宽，板凳长，扁担想绑在板凳上。") x 10,549,005 ops/sec ±1.08% (88 runs sampled)
isChinese("ss扁担宽，板凳长，扁担想绑在板凳上。") x 38,652,878 ops/sec ±5.66% (84 runs sampled)
isChinese("扁担宽，板凳长，扁担想绑在板凳上。ss") x 28,347,738 ops/sec ±2.94% (87 runs sampled)
isChinese(chars1000) true x 299,741 ops/sec ±1.77% (83 runs sampled)
isChinese(chars1000WithS) false x 1,571,945 ops/sec ±1.43% (83 runs sampled)
```

There is no improvement

**Comment by alsotang** [comment]
These ranges would be compiled to a regex. Maybe regex combines the range internally, so we don't need to do it manually?

**Comment by IWANABETHATGUY** [comment]
I am not suprised at all, the reason maybe list below
1. nodejs version, i used 14.x, and your nodejs version is 16.x, latest v8 engine maybe optimize regex
2. sort  punctuation list maybe put `，` , `。` at the back of list, our bench case only have these two punctuation, so the order of these two may effect a lot.
try to use the original pr version to verify my  guess

**Comment by IWANABETHATGUY** [comment]
image

**Comment by alsotang** [comment]
Maybe we should just trust the regex engine? I don't think the changes are necessary

**Comment by IWANABETHATGUY** [comment]
i agree with you

**Pull request closed without merging**
